name: Release

on:
  release:
    types: [released]

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repository
        uses: actions/checkout@v4

      - name: Check out build pipeline
        uses: actions/checkout@v4
        with:
          repository: 'hamelin-org/Hamelin'
          path: 'build'

      - name: Run pipeline
        run: dotnet run --project ./build/build/Hamelin.Build/Hamelin.Build.csproj
        env:
          Mode: Release
          Build__NuGetApiKey: ${{ secrets.NUGET_API_KEY }}
          Build__ProjectFile: 'src/Hamelin.Runtimes.GitHubActions/Hamelin.Runtimes.GitHubActions.csproj'
